fix-ci-cd PR

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -4,15 +4,24 @@ on:
   push:
     branches:
       - 'main'
-      - 'development'
+
   pull_request:
     branches:
       - 'main'
-      - 'development'
 
 jobs:
+  restrict-pr:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check PR source branch
+        if: github.event.pull_request.head.ref != 'development'
+        run: |
+          echo "Error: Only 'development' branch can be merged into 'main'."
+          exit 1
+
   testing:
     runs-on: ubuntu-latest
+    needs: restrict-pr
     name: 'Run unit test'
     steps:
       - uses: actions/checkout@v3
@@ -23,6 +32,7 @@ jobs:
         run: go test -v ./...
   build:
     runs-on: ubuntu-latest
+    needs: restrict-pr
     name: 'Run golang build'
     steps:
       - uses: actions/checkout@v3
@@ -34,6 +44,7 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
+    needs: testing
     name: 'Run automation deployment to EC2 instance'
     steps:
       - uses: actions/checkout@v3
